server:
  port: 8080
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:nisum_db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      hbm2ddl:
        auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        '[format_sql]': true
    sql:
      init:
        platform: h2
        mode: always
    main:
      allow-bean-definition-overriding: true
